name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            build: windows
          - os: ubuntu-latest
            build: linux
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish Artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.build }}
        path: IIDXClone/bin/Release/netcoreapp3.0
      
    
